# Copyright (C) 2025 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# https://pnpm.io/settings

# Keine Ausfuehrung von (pre-/post-) install-Skripten
# https://pnpm.io/settings#ignoredbuiltdependencies
ignoredBuiltDependencies: ["@prisma/client", "@prisma/engines"]

# https://pnpm.io/settings#minimumreleaseage
# 1 Tag = 24 * 60 Minuten
minimumReleaseAge: 1440

# Ausfuehrung von (pre-, post-) install-Skripte
# https://pnpm.io/settings#onlybuiltdependencies
onlyBuiltDependencies: [prisma]

# https://pnpm.io/settings#packagemanagerstrictversion
packageManagerStrictVersion: true

# https://pnpm.io/cli/add#--save-exact--e
saveExact: true

# https://pnpm.io/settings#saveprefix
savePrefix: ""
